### ISSUE TITLE
Sum of points for all quiz attempts ?

### ISSUE THREAD

**Issue by miroi** [academic-moodle-cooperation/moodle-gradereport_gradedist#8]
Hello,

I would like to ask if it is possible to have sum of all points of all quiz attempts per user ?

Thanks.

**Comment by goggo24** [comment]
You can do this with core functionality within grade overview: therefore create e.g. a grade category and assign all quiz items here (https://docs.moodle.org/310/en/Grade_categories) or add a manual grade item with calculation - (https://docs.moodle.org/310/en/Grade_calculations).
Because it's easier and more flexible to control it the way described above with core functionality - we won't change it in our report and i will close this issue.
